# site settings

title: L M
description: Welcome to my portfolio
taglong: Welcome to my portfolio!
tagshort: LM theme
url: https://souparathon.github.io/
baseurl: ""
permalink: pretty
repo: https://github.com/souparathon/souparathon.github.io

# author settings

author:
  name: Lilly Masie
  email: lilly.masie9@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  #facebook: username
  github: souparathon
  #instagram: username
  linkedin: lillymasie
  #stackoverflow: 0000000/username
  #twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
